version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: ${PROJECT}mysql
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  php:
    build: ./docker/php
    container_name: ${PROJECT}php
    ports: ['9000:9000']
    volumes: ['./symfony/:/var/www/symfony:cached']

  nginx:
    build: ./docker/nginx
    container_name: ${PROJECT}nginx
    ports: ['80:80']
    volumes: ['./symfony/:/var/www/symfony:cached']

  adminer:
    image: dockette/adminer:full
    container_name: ${PROJECT}adminer
    links:
      - mysql:mysql
    ports: ['8080:80']
    environment:
      UPLOAD: 1024M # upload_max_filesize, post_max_size