version: '3.7'
services:
  php:
    build: ./docker/php
    volumes: ['.:/var/www:cached']
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=api
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
  store-api:
    build: ./docker/nginx
    ports: ['8050:80']
    volumes: ['./store:/var/www/store:cached']